from __future__ import annotations


INDEX_HTML = r"""<!doctype html>
<html lang="pt-BR" data-theme="ultra-dark">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Painel do Robô — Home V4.1</title>
<style>
:root{color-scheme:dark;--bg:#010308;--bg2:#040a13;--panel:#06111d;--panel2:#081522;--line:#142a40;--line2:#214666;--ink:#f2f7fd;--muted:#93a7bb;--faint:#647b92;--blue:#2391ff;--cyan:#33d7ff;--green:#46df7d;--amber:#efbd63;--red:#ff656c;--shadow:rgba(0,0,0,.48)}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:var(--bg);color:var(--ink)}body{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;font-size:14px;line-height:1.5;background:radial-gradient(circle at 65% -10%,rgba(35,145,255,.12),transparent 34rem),var(--bg)}button,input,textarea{font:inherit}button{color:inherit}button:focus-visible,input:focus-visible,textarea:focus-visible,[tabindex]:focus-visible{outline:2px solid var(--cyan);outline-offset:2px}.hidden{display:none!important}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
.app{min-height:100vh;display:grid;grid-template-columns:222px minmax(0,1fr)}.side{position:sticky;top:0;height:100vh;border-right:1px solid var(--line);background:rgba(2,7,13,.96);padding:18px 14px;display:flex;flex-direction:column;gap:16px}.brand{display:flex;align-items:center;gap:10px;padding:4px 7px 10px}.brand-mark{width:42px;height:42px;display:grid;place-items:center;border:1px solid #23537d;background:#071827;border-radius:13px;font-size:22px}.brand strong{display:block;font-size:17px}.brand small{color:var(--muted)}.side-title{font-size:10px;text-transform:uppercase;letter-spacing:.12em;color:var(--faint);padding:0 7px}.state-list{display:grid;gap:7px}.state-control{border:1px solid var(--line);background:#040c15;border-radius:10px;padding:9px}.state-row{display:flex;align-items:center;justify-content:space-between;gap:8px}.state-name{font-weight:720}.state-value{font-size:10px;font-weight:850;color:var(--muted)}.state-value.good{color:var(--green)}.state-value.alert{color:var(--red)}.state-actions{display:flex;gap:5px;margin-top:7px}.mini{border:1px solid #22425f;background:#071522;border-radius:8px;padding:6px 8px;font-size:11px;font-weight:750;cursor:pointer;flex:1}.mini:hover{border-color:#3873a5;background:#0a1c2c}.mini.danger{border-color:#642830;color:#ff9da2;background:#210d12}.mini.safe{border-color:#1b5b37;color:#80eda4;background:#061e13}.mini:disabled{opacity:.45;cursor:not-allowed}.nav{display:grid;gap:4px}.nav button{border:1px solid transparent;background:transparent;border-radius:9px;text-align:left;padding:9px 10px;color:#b7c5d4;cursor:pointer}.nav button:hover{background:#07111c}.nav button.active{border-color:#20537e;background:#08192a;color:#bfe2ff;box-shadow:inset 2px 0 0 var(--blue)}.side-foot{margin-top:auto;border:1px solid #173047;border-radius:10px;background:#040c14;padding:10px;color:var(--muted);font-size:11px}.side-foot strong{color:var(--green)}
.main{min-width:0;padding:16px 20px 24px}.topline{height:48px;display:flex;align-items:center;justify-content:space-between;gap:14px;margin-bottom:10px}.title h1{font-size:20px;margin:0;letter-spacing:-.015em}.title p{margin:2px 0 0;color:var(--muted);font-size:12px}.session{border:1px solid var(--line);background:#06111c;border-radius:10px;padding:7px 10px;color:#bfcedd;font-size:11px}.status-strip{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));border:1px solid var(--line);background:linear-gradient(180deg,#07131f,#040b13);border-radius:13px;margin-bottom:10px;overflow:hidden}.status-item{min-height:58px;padding:10px 13px;display:flex;align-items:center;gap:9px;border-right:1px solid var(--line)}.status-item:last-child{border-right:0}.status-icon{width:28px;height:28px;border-radius:9px;border:1px solid #1e4565;background:#071623;display:grid;place-items:center}.status-item b{display:block;font-size:12px}.status-item span:last-child{font-size:11px;color:var(--muted)}.status-item.good span:last-child{color:var(--green)}.status-item.alert span:last-child{color:var(--red)}
.workspace{display:grid;grid-template-columns:minmax(0,1fr) 300px;gap:10px;min-height:calc(100vh - 160px)}.card{border:1px solid var(--line);background:linear-gradient(180deg,rgba(7,17,28,.98),rgba(3,9,15,.99));border-radius:13px;box-shadow:0 12px 30px var(--shadow)}.chat-card{min-height:660px;display:flex;flex-direction:column;overflow:hidden}.chat-head{display:flex;justify-content:space-between;gap:16px;padding:15px 17px;border-bottom:1px solid #10263a}.chat-head h2{font-size:16px;margin:0}.chat-head p{margin:2px 0 0;color:var(--muted);font-size:12px}.mode-proof{font-size:10px;border:1px solid #1f5e43;color:#7ce8a1;background:#062116;border-radius:999px;padding:5px 8px;align-self:center}.thread{flex:1;overflow:auto;padding:18px 20px;display:flex;flex-direction:column;gap:12px;min-height:360px}.bubble{max-width:78%;border:1px solid var(--line);padding:10px 12px;border-radius:12px;white-space:pre-wrap;word-break:break-word}.bubble.ai{align-self:flex-start;background:#07121d}.bubble.user{align-self:flex-end;background:linear-gradient(135deg,#0b3266,#124f9d);border-color:#2465a7}.bubble.system{align-self:stretch;max-width:100%;background:#052116;border-color:#17603a}.bubble-meta{display:block;margin-top:5px;color:#8ba1b7;font-size:10px}.goal-result{align-self:stretch;max-width:100%;border:1px solid #195b38;background:linear-gradient(90deg,rgba(4,45,25,.62),rgba(4,14,22,.96));border-radius:12px;padding:13px;display:none}.goal-result.failure{border-color:#71313a;background:linear-gradient(90deg,rgba(55,15,20,.65),rgba(4,14,22,.96))}.goal-result h3{margin:0 0 7px;font-size:14px}.result-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px}.result-stat{border-top:1px solid rgba(255,255,255,.08);padding-top:6px}.result-stat small{display:block;color:var(--muted)}.composer{border-top:1px solid #10263a;padding:12px 14px;background:#030a12}.composer-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px}.composer textarea{min-height:62px;max-height:160px;resize:vertical;width:100%;border:1px solid #20415f;background:#020812;color:var(--ink);border-radius:11px;padding:10px 12px}.send-icon{width:46px;border:1px solid #2475c3;background:linear-gradient(180deg,#1689ff,#0c61c4);border-radius:11px;cursor:pointer;font-size:18px}.action-row{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px}.action{border:1px solid #24547c;background:#071827;border-radius:10px;padding:9px 10px;cursor:pointer;text-align:left}.action b{display:block;font-size:12px}.action span{font-size:10px;color:var(--muted)}.action.execute{border-color:#1f6940;background:#062217}.action.execute b{color:#78e99e}.quick{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}.chip{border:1px solid #1b354d;background:#050f19;border-radius:999px;padding:6px 9px;color:#9fb4c7;font-size:10px;cursor:pointer}.chip:hover{border-color:#2d628e;color:#d8eaff}
.agent-card{padding:14px;align-self:start;position:sticky;top:75px}.agent-card h2{margin:0 0 12px;font-size:15px;color:#91cfff}.agent-status{border:1px solid #173c55;background:#05101a;border-radius:11px;padding:10px;margin-bottom:10px}.agent-status strong{display:block;font-size:18px;color:var(--green)}.kv{display:grid;grid-template-columns:92px 1fr;gap:0;border-top:1px solid #10263a}.kv:first-of-type{border-top:0}.kv dt,.kv dd{margin:0;padding:8px 0;font-size:11px}.kv dt{color:#8298ae}.kv dd{text-align:right;color:#c7d5e3;overflow-wrap:anywhere}.kv dd.good{color:var(--green)}.details-btn{width:100%;margin-top:10px;border:1px solid #21527b;background:#071725;border-radius:9px;padding:8px;cursor:pointer;color:#93ccff}
.secondary{display:none}.secondary.active{display:block}.secondary .card{padding:15px;margin-bottom:10px}.section-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:10px}.section-head h2{margin:0;font-size:16px}.muted{color:var(--muted)}.tasks{display:grid;gap:7px}.task{border:1px solid #152d43;background:#040d16;border-radius:9px;padding:9px;display:grid;grid-template-columns:1fr auto;gap:8px}.task small{color:var(--muted)}.task-status{font-size:10px;font-weight:800;color:#8ec7ff}.task[data-status=succeeded] .task-status{color:var(--green)}.task[data-status=failed] .task-status{color:var(--red)}.console{background:#010407;border:1px solid #11283b;border-radius:9px;min-height:240px;max-height:400px;overflow:auto;padding:10px;font:11px ui-monospace,SFMono-Regular,Consolas,monospace;color:#a9c0d6;white-space:pre-wrap}.log-tabs{display:flex;gap:5px;margin-bottom:8px}.log-tab{border:1px solid #19364f;background:#05101a;border-radius:999px;padding:5px 8px;color:#98adc2;font-size:10px;cursor:pointer}.log-tab.active{color:#c4e7ff;border-color:#2a6da4}.diag-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.diag-cell{border:1px solid #153048;border-radius:9px;background:#040d16;padding:10px}.config-row{display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #10263a;padding:10px 0}.switch{width:45px;height:25px;border:1px solid #3a4d60;border-radius:999px;background:#202b36;padding:2px;cursor:pointer}.switch span{display:block;width:19px;height:19px;border-radius:50%;background:#dbe5ee;transition:.15s}.switch.on{background:#0b67cb;border-color:#298cff}.switch.on span{transform:translateX(19px)}.btn{border:1px solid #214665;background:#071623;border-radius:9px;padding:8px 10px;cursor:pointer}.btn.danger{border-color:#6b2d35;background:#240d12;color:#ff9ea4}.btn.safe{border-color:#1c633c;background:#062117;color:#7de7a0}.explain{display:grid;grid-template-columns:1fr 1fr;gap:8px}.explain>div{border:1px solid #153048;background:#040d16;border-radius:9px;padding:9px}.tips{margin-top:10px;border:1px solid #153048;border-radius:9px;padding:10px;color:var(--muted)}
.toast{position:fixed;right:18px;bottom:18px;max-width:430px;background:#091827;border:1px solid #2c5274;border-radius:10px;padding:10px 12px;box-shadow:0 12px 35px rgba(0,0,0,.5);display:none;z-index:20}.busy{opacity:.6;pointer-events:none}
@media(max-width:1120px){.app{grid-template-columns:180px minmax(0,1fr)}.workspace{grid-template-columns:minmax(0,1fr) 260px}.result-grid{grid-template-columns:1fr 1fr}}
@media(max-width:860px){.app{grid-template-columns:1fr}.side{position:static;height:auto}.state-list{grid-template-columns:1fr 1fr}.nav{grid-template-columns:repeat(5,1fr)}.workspace{grid-template-columns:1fr}.agent-card{position:static}.status-strip{grid-template-columns:1fr 1fr}.status-item{border-bottom:1px solid var(--line)}.main{padding:12px}}
@media(max-width:560px){.state-list,.status-strip,.action-row,.result-grid,.diag-grid,.explain{grid-template-columns:1fr}.nav{grid-template-columns:1fr 1fr}.bubble{max-width:92%}.main{padding:8px}.thread{padding:12px}.session{display:none}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}
</style>
</head>
<body>
<div class="app">
<aside class="side" aria-label="Navegação e Controles de estado">
  <div class="brand"><div class="brand-mark" aria-hidden="true">▣</div><div><strong>Painel do Robô</strong><small>Home V4.1</small></div></div>
  <div class="side-title">Controles de estado</div>
  <div class="state-list">
    <div class="state-control"><div class="state-row"><span class="state-name">Central</span><span class="state-value" id="centralSideState">…</span></div><div class="state-actions"><button class="mini" id="centralAction">Aguarde</button></div></div>
    <div class="state-control"><div class="state-row"><span class="state-name">Robô</span><span class="state-value" id="robotSideState">…</span></div><div class="state-actions"><button class="mini" id="robotAction">Aguarde</button><button class="mini" id="robotRestart">↻</button></div></div>
    <div class="state-control"><div class="state-row"><span class="state-name">Desktop</span><span class="state-value" id="desktopSideState">…</span></div><div class="state-actions"><button class="mini" id="desktopAction">Alternar</button></div></div>
    <div class="state-control"><div class="state-row"><span class="state-name">Emergência</span><span class="state-value" id="emergencySideState">…</span></div><div class="state-actions"><button class="mini danger" id="emergencyAction">PARAR TUDO</button></div></div>
  </div>
  <div class="side-title">Navegação</div>
  <nav class="nav" aria-label="Seções do Painel">
    <button class="active" data-tab="home">⌂ Home</button>
    <button data-tab="tasksPage">☷ Tarefas</button>
    <button data-tab="historyPage">◴ Histórico</button>
    <button data-tab="diagnosticsPage">⌁ Diagnóstico</button>
    <button data-tab="configPage">⚙ Configurações</button>
  </nav>
  <div class="side-foot">Painel local: <strong>ONLINE</strong><br>127.0.0.1 · operação local</div>
</aside>
<main class="main">
  <header class="topline"><div class="title"><h1 id="pageTitle">Painel do Robô</h1><p id="pageSubtitle">Painel de Operação e Controle — conversa, execução e transparência.</p></div><div class="session" id="sessionBadge">● Sessão local ativa</div></header>

  <div class="status-strip" aria-label="Estado geral do sistema" aria-live="polite">
    <div class="status-item" id="centralStatus"><span class="status-icon">▤</span><div><b>Central</b><span>Consultando…</span></div></div>
    <div class="status-item" id="robotStatus"><span class="status-icon">▣</span><div><b>Robô local</b><span>Consultando…</span></div></div>
    <div class="status-item" id="systemStatus"><span class="status-icon">✓</span><div><b>Sistema</b><span>Consultando…</span></div></div>
    <div class="status-item" id="aiStatus"><span class="status-icon">✦</span><div><b>IA</b><span>Consultando…</span></div></div>
    <div class="status-item" id="emergencyStatus"><span class="status-icon">!</span><div><b>Emergência</b><span>Consultando…</span></div></div>
  </div>

  <section id="home" class="secondary active" aria-labelledby="conversationTitle">
    <div class="workspace">
      <article class="card chat-card">
        <div class="chat-head"><div><h2 id="conversationTitle">Conversar com a IA</h2><p>Pergunte sobre o projeto ou delegue um objetivo ao Robô de forma explícita.</p></div><span class="mode-proof">Conversa não executa</span></div>
        <div class="thread" id="thread" role="log" aria-live="polite" aria-relevant="additions">
          <div class="bubble ai">Sou a interface conversacional do projeto <b>project-memory</b>. Posso explicar o sistema, seu estado e suas capacidades sem executar ações.<span class="bubble-meta">IA conversacional · rota isolada</span></div>
          <div class="goal-result" id="goalResult"><h3 id="goalResultTitle">Objetivo concluído</h3><div id="goalResultText" class="muted"></div><div class="result-grid"><div class="result-stat"><small>Etapas</small><b id="resultSteps">—</b></div><div class="result-stat"><small>Readback</small><b id="resultReadback">—</b></div><div class="result-stat"><small>GoalVerifier</small><b id="resultVerifier">—</b></div><div class="result-stat"><small>IA usada</small><b id="resultAI">—</b></div></div></div>
        </div>
        <div class="composer">
          <label class="sr-only" for="messageInput">Mensagem ou objetivo</label>
          <div class="composer-row"><textarea id="messageInput" placeholder="Digite sua mensagem em linguagem natural…"></textarea><button id="sendArrow" class="send-icon" aria-label="Conversar">➤</button></div>
          <div class="action-row">
            <button class="action" id="conversationSend"><b>◌ Conversar</b><span>Responder sem executar ações no computador</span></button>
            <button class="action execute" id="executeGoal"><b>◎ Executar objetivo</b><span>Criar task e usar o Goal Runtime</span></button>
          </div>
          <div class="quick"><button class="chip" data-prompt="Em qual projeto você está e qual é o objetivo atual?">Sobre o projeto</button><button class="chip" data-exec="Abra um editor de texto">Abrir editor</button><button class="chip" data-exec="Liste os arquivos do diretório atual">Listar arquivos</button><button class="chip" data-exec="Abra o navegador">Navegar web</button><button class="chip" data-prompt="Resuma o estado atual do projeto sem executar nenhuma ação.">Resumo da sessão</button></div>
        </div>
      </article>

      <aside class="card agent-card" aria-labelledby="agentNowTitle"><h2 id="agentNowTitle">⌁ Agente agora</h2><div class="agent-status"><small class="muted">Status</small><strong id="agentStatusValue">Ocioso</strong></div><dl><div class="kv"><dt>Motor</dt><dd id="agentMotor">LOCAL</dd></div><div class="kv"><dt>Provider</dt><dd id="agentProvider">—</dd></div><div class="kv"><dt>Modelo</dt><dd id="agentModel">—</dd></div><div class="kv"><dt>Intent</dt><dd id="agentIntent">—</dd></div><div class="kv"><dt>Etapa atual</dt><dd id="agentStep">—</dd></div><div class="kv"><dt>GoalVerifier</dt><dd id="agentVerifier">—</dd></div><div class="kv"><dt>Task ID</dt><dd id="agentTaskId">—</dd></div><div class="kv"><dt>Duração</dt><dd id="agentDuration">—</dd></div></dl><button class="details-btn" id="agentDetails">Ver detalhes</button></aside>
    </div>
  </section>

  <section id="tasksPage" class="secondary"><div class="card"><div class="section-head"><div><h2>Tarefas</h2><div class="muted">Fila e tarefas recentes com estado real.</div></div><button class="btn" id="refreshBtn">↻ Atualizar</button></div><div class="tasks" id="tasks"><span class="muted">Carregando…</span></div></div></section>
  <section id="historyPage" class="secondary"><div class="card"><div class="section-head"><div><h2>Histórico</h2><div class="muted">Logs reais da aplicação e eventos recentes.</div></div></div><div class="log-tabs"><button class="log-tab active" data-log="all">Todos</button><button class="log-tab" data-log="panel">Painel</button><button class="log-tab" data-log="central">Central</button><button class="log-tab" data-log="robot">Robô</button></div><div id="logs" class="console">Aguardando log_events…</div></div></section>
  <section id="diagnosticsPage" class="secondary"><div class="card"><div class="section-head"><div><h2>Diagnóstico</h2><div class="muted">Saúde das dependências locais.</div></div><button class="btn" id="diagBtn">Executar diagnóstico</button></div><div id="diagnostics" class="diag-grid"><span class="muted">Ainda não executado.</span></div></div></section>
  <section id="configPage" class="secondary"><div class="card"><div class="section-head"><div><h2>Configurações</h2><div class="muted">Capacidades locais e segurança.</div></div></div><div class="config-row"><div><b>Controle do Desktop</b><div class="muted">Mouse, teclado, aplicativos e percepção física.</div></div><div id="desktopSwitch" class="switch" role="switch" aria-checked="false" tabindex="0"><span></span></div></div><div class="config-row"><div><b>Parada de emergência</b><div class="muted">Independente do planner e do provider.</div></div><div><button class="btn danger" data-action="emergency/trigger">PARAR TUDO</button> <button class="btn safe" data-action="emergency/clear">Liberar emergência</button></div></div><div class="config-row"><div><b>Laboratório de comandos guiados</b><div class="muted">Dicas rápidas: entenda comandos técnicos antes de executá-los.</div></div></div><div style="margin-top:10px"><label for="guidedCommand" class="sr-only">Comando guiado</label><input id="guidedCommand" style="width:100%;padding:9px;border:1px solid #20415f;background:#020812;color:var(--ink);border-radius:9px" placeholder="Ex.: git pull"><div style="margin-top:7px"><button class="btn" id="explainBtn">Explicar comando</button></div><div id="explanation" class="explain"></div><div class="tips">Dicas rápidas — esta área explica comandos conhecidos; texto desconhecido não vira shell remoto.</div></div></div></section>
</main>
</div>
<div id="toast" class="toast" role="status" aria-live="polite"></div>
<script>
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);let latestStatus=null;let logSource='all';let lastConversationMeta=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(text){const el=$('#toast');el.textContent=text;el.style.display='block';clearTimeout(el._timer);el._timer=setTimeout(()=>el.style.display='none',4200)}
async function api(path,opts={}){const r=await fetch(path,opts);const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.detail||data.message||r.statusText);return data}
function setStatus(id,good,text,alert=false){const el=$(id);el.classList.toggle('good',good&&!alert);el.classList.toggle('alert',alert);el.querySelector('span:last-child').textContent=text}
function button(el,action,label,kind=''){el.textContent=label;el.className='mini '+kind;el.disabled=!action;el.onclick=action?()=>runAction(action):null}
function renderSide(s){const c=$('#centralSideState'),r=$('#robotSideState'),d=$('#desktopSideState'),e=$('#emergencySideState');c.textContent=s.central.online?'ONLINE':'OFFLINE';c.className='state-value '+(s.central.online?'good':'');r.textContent=s.robot.online?'ONLINE':'OFFLINE';r.className='state-value '+(s.robot.online?'good':'');d.textContent=s.desktop.enabled?'ATIVO':'INATIVO';d.className='state-value '+(s.desktop.enabled?'good':'');e.textContent=s.emergency.active?'ATIVA':'NORMAL';e.className='state-value '+(s.emergency.active?'alert':'good');
 if(s.central.online&&s.central.managed)button($('#centralAction'),'central/stop','Parar','danger');else if(s.central.online)button($('#centralAction'),null,'Externa');else button($('#centralAction'),'central/start','Ligar','safe');
 if(s.robot.online)button($('#robotAction'),'robot/stop','Parar','danger');else if(s.emergency.active)button($('#robotAction'),null,'Bloqueado');else button($('#robotAction'),'robot/start','Ligar','safe');button($('#robotRestart'),s.emergency.active?null:'robot/restart','↻','');
 button($('#emergencyAction'),s.emergency.active?'emergency/clear':'emergency/trigger',s.emergency.active?'Liberar':'PARAR TUDO',s.emergency.active?'safe':'danger');
 $('#desktopAction').onclick=toggleDesktop;
}
function renderStatus(s){setStatus('#centralStatus',s.central.online,s.central.online?'Online':'Offline');setStatus('#robotStatus',s.robot.online,s.robot.online?'Online':'Offline');setStatus('#systemStatus',s.desktop.enabled&&!s.emergency.active,s.emergency.active?'Bloqueado':(s.desktop.enabled?'Saudável':'Desktop inativo'),s.emergency.active);setStatus('#aiStatus',!!s.ai?.available,s.ai?.available?'Disponível':'Indisponível');setStatus('#emergencyStatus',!s.emergency.active,s.emergency.active?'ATIVA':'Normal',s.emergency.active)}
function renderTasks(tasks){$('#tasks').innerHTML=tasks.length?tasks.map(t=>`<div class="task" data-status="${esc(t.status)}"><div><b>${esc(t.command)}</b><br><small>${esc(t.id)} · tentativa ${esc(t.attempts)}</small></div><span class="task-status">${esc(t.status)}</span></div>`).join(''):'<span class="muted">Nenhuma tarefa registrada.</span>'}
function renderLogs(){if(!latestStatus)return;let events=latestStatus.log_events||[];if(logSource!=='all')events=events.filter(e=>e.component===logSource);$('#logs').innerHTML=events.length?events.map(e=>`[${esc(e.component).toUpperCase()}] ${esc(e.line)}`).join('\n'):'Nenhum evento neste filtro.'}
function taskTelemetry(task){if(!task)return null;const result=task.result||{};let verifier='—';if(task.status==='succeeded'&&result.goal_completed===true&&result.verified===true)verifier='SUCCEEDED';else if(task.status==='failed')verifier='FAILED';else if(task.status==='running')verifier='VERIFICANDO/EXECUTANDO';const provider=result.planner_provider&&result.planner_provider!=='deterministic'?result.planner_provider:null;return {status:task.status,provider,model:result.planner_model||null,intent:result.intent||result.goal_intent||'—',step:result.current_step||result.steps_completed||'—',verifier,id:task.id,duration:duration(task),ai:!!provider}}
function duration(task){if(!task?.created_at||!task?.updated_at)return '—';const ms=new Date(task.updated_at)-new Date(task.created_at);if(!Number.isFinite(ms)||ms<0)return '—';return `${Math.round(ms/1000)}s`}
function renderAgent(tasks){const t=taskTelemetry(tasks?.[0]);if(!t){$('#agentStatusValue').textContent='Ocioso';return}const statusMap={queued:'Enfileirado',running:'Executando',succeeded:'Concluído',failed:'Falhou'};$('#agentStatusValue').textContent=statusMap[t.status]||t.status;$('#agentProvider').textContent=t.provider||'—';$('#agentModel').textContent=t.model||'—';$('#agentIntent').textContent=t.intent;$('#agentStep').textContent=t.step;$('#agentVerifier').textContent=t.verifier;$('#agentVerifier').className=t.verifier==='SUCCEEDED'?'good':'';$('#agentTaskId').textContent=t.id;$('#agentDuration').textContent=t.duration;$('#agentMotor').textContent=t.provider?'IA + LOCAL':'LOCAL';
 const task=tasks[0],result=task.result||{};if(task.status==='succeeded'&&result.goal_completed===true&&result.verified===true){showGoalResult(task,t)}else if(task.status==='failed'){showGoalResult(task,t,true)}}
function showGoalResult(task,t,failure=false){const box=$('#goalResult');box.style.display='block';box.classList.toggle('failure',failure);$('#goalResultTitle').textContent=failure?'Objetivo não concluído':'Objetivo concluído';$('#goalResultText').textContent=failure?(task.error||'A execução terminou sem satisfazer todos os critérios.'):task.command;$('#resultSteps').textContent=task.result?.steps_completed??'completas';$('#resultReadback').textContent=task.result?.verified===true?'Confirmado':'—';$('#resultVerifier').textContent=t.verifier;$('#resultAI').textContent=t.ai?'SIM':'NÃO'}
async function refresh(){try{const s=await api('/api/status');latestStatus=s;renderSide(s);renderStatus(s);renderTasks(s.tasks||[]);renderLogs();renderAgent(s.tasks||[]);$('#desktopSwitch').classList.toggle('on',s.desktop.enabled);$('#desktopSwitch').setAttribute('aria-checked',String(!!s.desktop.enabled))}catch(e){toast('Falha ao atualizar: '+e.message)}}
async function runAction(name){try{const r=await api('/api/'+name,{method:'POST'});toast(r.message||'Ação concluída.');await refresh()}catch(e){toast('Erro: '+e.message);await refresh()}}
function appendBubble(kind,text,meta=''){const el=document.createElement('div');el.className='bubble '+kind;el.textContent=text;if(meta){const m=document.createElement('span');m.className='bubble-meta';m.textContent=meta;el.appendChild(m)}$('#thread').appendChild(el);$('#thread').scrollTop=$('#thread').scrollHeight;return el}
async function converse(){const input=$('#messageInput'),message=input.value.trim();if(!message)return toast('Digite uma mensagem.');appendBubble('user',message,'Você · conversa');input.value='';setBusy(true);try{const r=await api('/api/conversation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message})});lastConversationMeta=r;appendBubble('ai',r.reply,`${r.provider} · ${r.model} · contexto ${r.context_version}`)}catch(e){appendBubble('ai','Não consegui obter uma resposta da IA agora. '+e.message,'Conversa · falha segura')}finally{setBusy(false)}}
async function executeGoal(){const input=$('#messageInput'),command=input.value.trim();if(!command)return toast('Digite um objetivo.');appendBubble('user',command,'Você · objetivo para execução');input.value='';setBusy(true);try{const task=await api('/api/tasks',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command})});appendBubble('system',`Objetivo enfileirado. Task ID: ${task.id}`,'Goal Runtime aguardando execução');toast('Objetivo enviado para o Robô.');await refresh()}catch(e){appendBubble('system','Objetivo não foi enfileirado: '+e.message,'Execução não iniciada')}finally{setBusy(false)}}
function setBusy(b){$('#conversationSend').classList.toggle('busy',b);$('#executeGoal').classList.toggle('busy',b);$('#sendArrow').classList.toggle('busy',b)}
async function toggleDesktop(){if(!latestStatus)return;const enabled=!latestStatus.desktop.enabled;try{const r=await api('/api/desktop',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled})});toast(r.message+(r.restart_required?' Reinicie o Robô.':''));await refresh()}catch(e){toast('Erro: '+e.message)}}
async function diagnostics(){try{const d=await api('/api/diagnostics'),x=d.desktop;$('#diagnostics').innerHTML=[['Python',d.python.supported],['X11',x.x11_detected],['PyAutoGUI',x.pyautogui_installed],['xdotool',!!x.xdotool],['scrot',!!x.scrot],['Desktop',x.enabled]].map(([n,ok])=>`<div class="diag-cell"><b>${n}</b><br><span class="${ok?'good':'muted'}">${ok?'✓ OK':'verificar'}</span></div>`).join('')}catch(e){toast('Erro: '+e.message)}}
function showTab(id){$$('.secondary').forEach(x=>x.classList.toggle('active',x.id===id));$$('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));const labels={home:['Painel do Robô','Painel de Operação e Controle — conversa, execução e transparência.'],tasksPage:['Tarefas','Fila operacional real.'],historyPage:['Histórico','Logs reais da aplicação.'],diagnosticsPage:['Diagnóstico','Saúde das dependências locais.'],configPage:['Configurações','Capacidades e segurança local.']};$('#pageTitle').textContent=labels[id][0];$('#pageSubtitle').textContent=labels[id][1]}
$$('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));$$('[data-action]').forEach(b=>b.onclick=()=>runAction(b.dataset.action));$$('.log-tab').forEach(b=>b.onclick=()=>{$$('.log-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');logSource=b.dataset.log;renderLogs()});$$('[data-prompt]').forEach(b=>b.onclick=()=>{$('#messageInput').value=b.dataset.prompt;converse()});$$('[data-exec]').forEach(b=>b.onclick=()=>{$('#messageInput').value=b.dataset.exec});
$('#conversationSend').onclick=converse;$('#sendArrow').onclick=converse;$('#executeGoal').onclick=executeGoal;$('#messageInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();converse()}});$('#refreshBtn').onclick=refresh;$('#diagBtn').onclick=diagnostics;$('#desktopSwitch').onclick=toggleDesktop;$('#desktopSwitch').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggleDesktop()}});$('#agentDetails').onclick=()=>showTab('tasksPage');
$('#explainBtn').onclick=async()=>{const command=$('#guidedCommand').value.trim();if(!command)return toast('Digite um comando.');try{const r=await api('/api/guided/explain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command})});$('#explanation').innerHTML=`<div><b>O que faz</b><br>${esc(r.what)}</div><div><b>Por que</b><br>${esc(r.why)}</div><div><b>Esperado</b><br>${esc(r.expected)}</div><div><b>Onde</b><br>${esc(r.where)}</div>`}catch(e){toast('Erro: '+e.message)}};
refresh();setInterval(refresh,2500);
</script>
</body>
</html>"""


__all__ = ["INDEX_HTML"]
